### ISSUE TITLE
there is not exist uncertainty.py file

### ISSUE THREAD

**Issue by WenLinLliu** [fiveai/MoCaE#1]

**Comment by WenLinLliu** [comment]
File "/mnt/d/work/06/MoCaE-main/mmdet/core/utils/__init__.py", line 8, in <module>
    from .uncertainty import Uncertainty
ModuleNotFoundError: No module named 'mmdet.core.utils.uncertainty'

**Comment by selimkuzucu** [comment]
Hi @WenLinLliu , thanks for your interest in our work and bringing this issue to our attention. The newest commit (aa6e81f9a7e2caa1e550315f12e97882e4a0cba4) should resolve the problem. Please let me know if the issue persists and/or if you face any further problems.
