### ISSUE TITLE
dotav1

### ISSUE THREAD

**Issue by liutianyi00** [fiveai/MoCaE#3]
Can I reproduce your 82.62AP result on dotav1 in a simple way please?

**Comment by selimkuzucu** [comment]
Hi @liutianyi00, we thank you for your interest in our work and apologize for the delayed response. I have just committed some new changes (9abce59f76055fd184e25efcf8ae59c27fce0dab) that should greatly simplify this process. Please take a look at Issue https://github.com/fiveai/MoCaE/issues/2 which is the duplicate of this. Do let us know if you face any further issues while using our code or reproducing our results.

**Comment by kemaloksuz** [comment]
@liutianyi00 - Please refer [here](https://github.com/fiveai/MoCaE/tree/main?tab=readme-ov-file#reproducing-rotated-object-detection-results) to reproduce our results. I am closing the issue now. Feel free to let us know and reopen this issue if you have any questions or difficulties.
